# Screen/Window constants
TITLEWIDTH = 16
TITLEHEIGHT = 16
NROWS = 36
NCOLS = 28
SCREENWIDTH = NCOLS * TITLEWIDTH
SCREENHEIGHT = NROWS * TITLEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)
BLACK = (0, 0, 0)

# Pac-Man constants
YELLOW = (255, 255, 0)
STOP = 0
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2
PORTAL = 3

PACMAN = 0
PELLET = 1
POWERUPPELLET = 2

# Node constants
WHITE = (255, 255, 255)
RED = (255, 0, 0)

# Ghost constants
GHOST = 3
SCATTER = 0
CHASE = 1
FREIGHT = 2
SPAWN = 3
